[package]
name = "gamedim"
version = "0.1.0"
authors = ["Juergen Stuber <juergen@jstuber.net>"]
description = "Library for two- or three-dimensional coordinates and arrays."
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
rand = "0.8.1"
